model:
  model_id: "/home/xucong24/Compiler/work_dirs/passformer_gallvm_seq2seq_concat/20260120_195517/final_model"
  encoder_tokenizer_id: "/home/xucong24/Compiler/checkpoints/Inst2VecTokenizer"
  decoder_tokenizer_id: "/home/xucong24/Compiler/checkpoints/OptiSeqTokenizer"

data:
  bc_files:
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_adpcm.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_bitcount.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_blowfish.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_bzip2.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_crc32.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_dijkstra.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_gsm.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_ispell.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_jpeg-c.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_jpeg-d.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_lame.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_patricia.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_qsort.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_rijndael.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_sha.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_stringsearch.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_stringsearch2.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_susan.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_tiff2bw.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_tiff2rgba.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_tiffdither.bc"
    - "/home/xucong24/Compiler/datasets/cbench-v1/benchmark_cbench-v1_tiffmedian.bc"
  max_length: 512

rl:
  # num_rollouts: 8
  max_gen_length: 32
  num_rollouts: 16
  num_reward_workers: 16
  temperatures: [0.3, 0.5, 0.7, 1.0]   # 低温(利用) / 中温(平衡) / 高温(探索)
  # temperature: 0.7    
  gamma: 0.99
  entropy_coeff: 0.01
  kl_coeff: 0.0
  max_grad_norm: 1.0
  reward_norm: true

output:
  base_work_dir: "/home/xucong24/Compiler/work_dirs/reinforce_sequential"

training:
  learning_rate: 5e-7
  batch_size: 1
  epochs_per_benchmark: 500     # 每个 benchmark 最多训练的 epoch 数
  reward_threshold: 10        # 平均 reward 达到此值则提前切换到下一个 benchmark
  patience: 500                  # 连续多少个 epoch reward 没有提升则提前切换
  replay_ratio: 0.0            # 每训练一个 benchmark 后，回放已训练 benchmark 的概率
  replay_epochs: 2             # 每次回放轮数
  save_steps: 50
  log_steps: 1
